spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            discovery:
                locator:
                  enabled: true
                  lower-case-service-id: true

Server:
  port: 8888

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0


